Arewa Data Science Academy


Deep Learning Cohort1.0

Name:  Abdullahi Ahmad

Email: abdulll8392@gmail.com

Title: Week 1 Solution

Exercises Solution

 1) Create a random tensor with shape (7, 7)

In [2]:
#Solution
import torch #importing the pytorch

tensor_random = torch.rand((7,7)) #specifying the shape with is 7,7

print(tensor_random)

tensor([[0.3315, 0.3765, 0.2812, 0.0876, 0.7503, 0.5333, 0.1909],
        [0.7413, 0.9086, 0.1033, 0.2663, 0.4166, 0.6682, 0.0345],
        [0.2555, 0.9133, 0.4498, 0.1540, 0.3311, 0.1628, 0.1795],
        [0.1812, 0.3914, 0.3466, 0.1357, 0.5269, 0.9333, 0.2722],
        [0.5040, 0.8829, 0.5971, 0.1175, 0.9955, 0.7124, 0.6587],
        [0.9399, 0.0077, 0.1152, 0.5529, 0.8745, 0.9115, 0.4949],
        [0.8906, 0.4216, 0.9711, 0.8020, 0.7504, 0.6623, 0.3465]])


3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
second_tensor = torch.rand((1,7))

transpose_tensor = torch.transpose(second_tensor,0,1)
print(transpose_tensor)

tensor([[0.8071],
        [0.7659],
        [0.8019],
        [0.0806],
        [0.6702],
        [0.4216],
        [0.3141]])


In [6]:
mult_tensor = torch.mm(tensor_random,transpose_tensor,out=None)

In [7]:
print(mult_tensor)

tensor([[1.5760],
        [1.9702],
        [1.6258],
        [1.5669],
        [2.7457],
        [2.0273],
        [2.7761]])


4. Set the random seed to 0 and do 2 & 3 over again.

In [12]:
random_seed = 0
torch.manual_seed(random_seed)
tensor_random = torch.rand((7,7))
print(tensor_random)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


In [14]:
torch.manual_seed(random_seed)
second_tensor = torch.rand((1,7))
transpose_tensor = torch.transpose(second_tensor,0,1)
print(transpose_tensor)

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])


In [16]:
mult_tensor = torch.mm(tensor_random,transpose_tensor,out=None)
print(mult_tensor)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [17]:
random_seed = 1234
torch.manual_seed(random_seed)
tensor_GPU_rand = torch.rand((7,7))
print(tensor_GPU_rand)

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])


Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [18]:
random_seed = 1234
torch.manual_seed(random_seed)
rand_1 = torch.rand((2,3))
rand_2 = torch.rand((2,3))

In [19]:
print(rand_1)
print(rand_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
rand_1 = torch.rand((2,3))
rand_2 = torch.rand((2,3))

In [20]:
#reshaping the second tensor before performing the calculations
rand_2 = torch.reshape(rand_2,(3,2))

In [21]:
mult_rand = torch.mm(rand_1,rand_2)

In [22]:
print(mult_rand)

tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]])


8. Find the maximum and minimum values of the output of 7.

In [23]:
min_7 = torch.min(mult_rand)
print(min_7)

tensor(0.2931)


In [24]:
max_7 = torch.max(mult_rand)
print(max_7)

tensor(0.6074)


9. Find the maximum and minimum index values of the output of 7.

In [25]:
min_arg_7 = torch.argmin(mult_rand)
print(min_arg_7)

tensor(1)


In [26]:
max_arg_7 = torch.argmax(mult_rand)
print(max_arg_7)

tensor(2)


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [28]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
rand_tens = torch.rand(1,1,1,10)

# Remove single dimensions
new_tens = rand_tens.squeeze()

# Print out tensors and their shapes
print(rand_tens , rand_tens.shape)
print(new_tens , new_tens.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
